### ISSUE TITLE
Crontab

### ISSUE THREAD

**Issue by Wolly300** [motey/Ark-docker#1]
Crontab is not running:

Id doesn't matter which command I run, always get this error:

"/tmp/steam.crontab":11: bad minute

#
0 0 * * * arkmanager update --warn --update-mods >> /ark/log/crontab.log 2>&1
0 0 * * * arkmanager backup >> /ark/log/crontab.log 2>&1
#

**Comment by motey** [comment]
Fixed with https://github.com/motey/Ark-docker/releases/tag/1.2-motey
Image available at https://hub.docker.com/r/motey/arkserver

`docker pull motey/arkserver`
or
`docker-compose pull`

**Comment by motey** [comment]
Hi Wolly, could you please verify the fix

**Comment by Wolly300** [comment]
Seems to work. How did you fix it?

**Comment by motey** [comment]
https://github.com/motey/Ark-docker/commit/12164088267474cdd06256f0dc2102ce2dfb5b60

There was an typo in the upstream image

**Comment by cowza** [comment]
I'm getting this exact issue again, can confirm i've got the latest image.
