### ISSUE TITLE
Enable Mod(Permission denied on main.cfg)

### ISSUE THREAD

**Issue by xXValiXx** [motey/Ark-docker#3]
If you start the docker like it is described on the README it will download everything and start the server. If the server is up i wanted to install some mods. That worked completely fine. After that i had to enable them via arkmanager enablemod xxxxx. 
I did get a permission denied.
```
$ arkmanager enablemod 895711211
Running command 'enablemod' for instance 'main'
/usr/local/bin/arkmanager: line 2888: /etc/arkmanager/instances/main.cfg: Permission denied
```
i did change the owner rights to the main.cfg with
```
chown steam:root /etc/arkmanager/instances/main.cfg
```
That worked for me and i was able to enable mods

**Comment by motey** [comment]
This should work now  without the workaround. need to verifiy
